### ISSUE TITLE
Fortran compilation error

### ISSUE THREAD

**Issue by akhilsnair2017** [hczhai/PGOPT#1]
Hi,
I have tried to install PGOPT in our supercomputer but getting a compilation error as  "fatal error: Python.h: No such file or directory
 "tmp/tmpt5mnnwcc/src.linux-x86_64-3.6/fortranobject.h:7:20: fatal error: Python.h: No such file or directory
#include "Python.h"

 I have tried to directly install without via docker as gfortran , python, etc. are already installed in our supercomputer.

Any help to solve this problem would be appreciated

**Comment by hczhai** [comment]
Find the path to `Python.h` in your system, then add `--include-paths <path1>:<path2>:..` in https://github.com/hczhai/PGOPT/blob/master/ACNN/formod/Makefile#L7
