### ISSUE TITLE
Enquiry about adjusting the supported cluster structure generation

### ISSUE THREAD

**Issue by akhilsnair2017** [hczhai/PGOPT#3]
Hi,
I have been successful in constructing Pt9 cluster supported on CeO2 surface using  PGOPT program. However, many of the structures generated contain the cluster located at the edges of computational unit cell also with too short bond distance from the surface. I am attaching an image of  such a structure here for reference. It would be helpful if any explanation of any parameters for adjusting the location of cluster within the unit cell and the distance of clusters from support can be provided if they are available in PGOPT code

Thanks in advance
![Screenshot (131)](https://user-images.githubusercontent.com/47722853/117529890-e2b18600-aff7-11eb-858c-e9291a21ff83.png)

**Comment by hczhai** [comment]
To move the cluster into the center, you need a correct "unit_cell" (which is smaller than computational cell) in your input file. https://github.com/hczhai/PGOPT/blob/27577ca27b0fa0e20d61caa722461854b652c7bd/ACNN/tests/structure_generation/pt7-alpha.json#L24-L30
